name: "${project_name}"
version: "${project_version}"
description: "${project_description}"
main: "tech.execsuroot.jarticle.JarticlePlugin"
author: "execsuroot"
website: "execsuroot.tech"
api-version: "1.20"
